### ISSUE TITLE
node_modules/async/dist/async.js:966

### ISSUE THREAD

**Issue by asdrubalos** [aquasecurity/cloudsploit#1158]
/var/scan/cloudsploit/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /var/scan/cloudsploit/node_modules/async/dist/async.js:966:32
    at /var/scan/cloudsploit/node_modules/async/dist/async.js:3685:13
    at Timeout._onTimeout (/var/scan/cloudsploit/engine.js:204:45)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by D00gs** [comment]
hiya. this is the same issue as here. I have listed a workaround to try until an official fix comes out https://github.com/aquasecurity/cloudsploit/issues/960#issuecomment-1005152782
