### ISSUE TITLE
Azure no result 

### ISSUE THREAD

**Issue by Vbubblery** [aquasecurity/cloudsploit#1728]
The config.js include the current credential for azure, and i use the command belong to generate the report
```
./index.js --json=azure.json --junit=azure.xml --cloud=azure --config=./config.js
```
But it throw the issue, and nothing return to json and xml file.

```
url: https://management.azure.com//subscriptions/78131263-201b-4c2e-8ba9-57731b087025/resourceGroups/rg-flowlity-global/providers/Microsoft.Storage/storageAccounts/stdatasynctrigger/listKeys?api-version=2019-06-01 obj: {"url":"https://management.azure.com//subscriptions/78131263-201b-4c2e-8ba9-57731b087025/resourceGroups/rg-flowlity-global/providers/Microsoft.Storage/storageAccounts/stdatasynctrigger/listKeys?api-version=2019-06-01","post":true,"rateLimit":3000} localData: undefined

INFO: Metadata collection complete. Analyzing...
INFO: Analysis complete. Scan report to follow...
Plugin Virtual Network Peering returned no results. There may be a problem with this plugin.
Plugin VM Desired SKU Size returned no results. There may be a problem with this plugin.
Plugin VM Approved Extensions returned no results. There may be a problem with this plugin.
/home/bubble/cloudsploit/helpers/azure/functions.js:203
    if (!policyAssignmentStatus.length) {
                                ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.checkPolicyAssignment (/home/bubble/cloudsploit/helpers/azure/functions.js:203:33)
    at /home/bubble/cloudsploit/plugins/azure/securitycenter/monitorBlobEncryption.js:24:21
    at /home/bubble/cloudsploit/node_modules/async/dist/async.js:3113:16
    at eachOfArrayLike (/home/bubble/cloudsploit/node_modules/async/dist/async.js:1072:9)
    at eachOf (/home/bubble/cloudsploit/node_modules/async/dist/async.js:1120:5)
    at Object.eachLimit (/home/bubble/cloudsploit/node_modules/async/dist/async.js:3175:5)
    at Object.run (/home/bubble/cloudsploit/plugins/azure/securitycenter/monitorBlobEncryption.js:19:15)
    at /home/bubble/cloudsploit/engine.js:223:28
    at /home/bubble/cloudsploit/node_modules/async/dist/async.js:3685:9
    at replenish (/home/bubble/cloudsploit/node_modules/async/dist/async.js:1014:17)
```

Is Azure api updated?

**Comment by tudorghigheanu** [comment]
i see the same error.

**Comment by MateuszBelczowski** [comment]
If I understand it correctly, this is the commit that broke this -> https://github.com/aquasecurity/cloudsploit/commit/8415d5c05288a836313838523233a3347e56bbe6#diff-e820abec8c98dc12e01a66376533a10a5099daba4f6accc37668721b03fd2aa4R200

and it would be enough to just add default value 

```js
policyAssignmentStatus =  defualtPolicyAssignments[param] || '';
```

Is that correct?

**Comment by jmeit-fwdsec** [comment]
> If I understand it correctly, this is the commit that broke this -> [8415d5c#diff-e820abec8c98dc12e01a66376533a10a5099daba4f6accc37668721b03fd2aa4R200](https://github.com/aquasecurity/cloudsploit/commit/8415d5c05288a836313838523233a3347e56bbe6#diff-e820abec8c98dc12e01a66376533a10a5099daba4f6accc37668721b03fd2aa4R200)
> 
> and it would be enough to just add default value
> 
> ```js
> policyAssignmentStatus =  defualtPolicyAssignments[param] || '';
> ```
> 
> Is that correct?

This works for me, and makes sense based on helpers/azure/functions.js:196-201

**Comment by alphadev4** [comment]
Hi @Vbubblery can you check now?

**Comment by alphadev4** [comment]
hi @telekomancer , i see you have added the credentials in config.js file but your attributes for the object are commented out. Can you try out like this in config.js file 
azure: {
            // OPTION 1: If using a credential JSON file, enter the path below
            credential_file: '/home/username/tools/cloudsploit/creds.json',
            // OPTION 2: If using hard-coded credentials, enter them below
            application_id: my-app-id-on-azure,
            key_value: .string~of.keyvalue...,
            directory_id: my-dir-id-on-azure,
            subscription_id: my-subs-id-on-azure
        },

**Comment by telekomancer** [comment]
Oh! Actually, that was the options that i changed, i had to make some changes at code (https://github.com/aquasecurity/cloudsploit/issues/1728#issuecomment-1773289090) and some changes at config.js level and everything works.

Thanks for the help!

**Comment by alphadev4** [comment]
@Vbubblery Can we close this now?
