### ISSUE TITLE
Unable to run the cloudsploit scan 

### ISSUE THREAD

**Issue by dharmendralakhara67** [aquasecurity/cloudsploit#2059]
Hi Team,

While running the scan facing below issue can anyone help on this 

$ ./index.js --config /opt/cloudsploit/config.js --json out.json

   _____ _                 _  _____       _       _ _   
  / ____| |               | |/ ____|     | |     (_) |  
 | |    | | ___  _   _  __| | (___  _ __ | | ___  _| |_ 
 | |    | |/ _ \| | | |/ _` |\___ \| '_ \| |/ _ \| | __|
 | |____| | (_) | |_| | (_| |____) | |_) | | (_) | | |_ 
  \_____|_|\___/ \__,_|\__,_|_____/| .__/|_|\___/|_|\__|
                                   | |                  
                                   |_|                  

  CloudSploit by Aqua Security, Ltd.
  Cloud security auditing for AWS, Azure, GCP, Oracle, and GitHub

INFO: Using CloudSploit config file: /opt/cloudsploit/config.js
INFO: Skipping AWS pagination mode
INFO: Determining API calls to make...
INFO: Found 356 API calls to make for aws plugins
INFO: Collecting metadata. This may take several minutes...
(node:34) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
(Use `node --trace-warnings ...` to show where the warning was created)
/opt/cloudsploit/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error [TypeError]: collection[serviceLower][callKey][region].data.concat is not a function
    at executorCb (/opt/cloudsploit/collectors/aws/collector.js:154:129)
    at /opt/cloudsploit/collectors/aws/collector.js:197:37
    at /opt/cloudsploit/node_modules/async/dist/async.js:4620:26
    at Response.<anonymous> (/opt/cloudsploit/collectors/aws/collector.js:194:48)
    at Request.<anonymous> (/opt/cloudsploit/node_modules/aws-sdk/lib/request.js:367:18)
    at Request.callListeners (/opt/cloudsploit/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/cloudsploit/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/cloudsploit/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/opt/cloudsploit/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/cloudsploit/node_modules/aws-sdk/lib/state_machine.js:14:12) {
  code: 'TypeError',
  time: 2024-07-03T11:21:13.144Z
}

Node.js v18.19.1

**Comment by mebibite** [comment]
I'm experiencing the same issue. This used to work before, nothing was changed in the configuration files.

**Comment by ihan97** [comment]
Encountered the same issue with version v3.5.0. Rolled back to v3.4.0 and no issues there.

**Comment by mebibite** [comment]
Thanks for the feedback, ihan97! Hope the Cloudsploit team fixes the root cause as well.

**Comment by aravindsv619** [comment]
I am also getting the same error.
Please migrate your code to use AWS SDK for JavaScript (v3).

For more information, check the blog post at https://a.co/cUPnyil

/home/aravind/Tools/cloudsploit/node_modules/aws-sdk/lib/request.js:31

            throw err;

            ^



Error [TypeError]: AWS[serviceName] is not a constructor

    at /home/aravind/Tools/cloudsploit/collectors/aws/collector.js:139:119

    at /home/aravind/Tools/cloudsploit/node_modules/async/dist/async.js:3113:16

    at replenish (/home/aravind/Tools/cloudsploit/node_modules/async/dist/async.js:1014:17)

    at /home/aravind/Tools/cloudsploit/node_modules/async/dist/async.js:1019:9

    at Object.eachLimit$1 (/home/aravind/Tools/cloudsploit/node_modules/async/dist/async.js:3199:24)

    at /home/aravind/Tools/cloudsploit/collectors/aws/collector.js:109:23

    at replenish (/home/aravind/Tools/cloudsploit/node_modules/async/dist/async.js:1014:17)

    at /home/aravind/Tools/cloudsploit/node_modules/async/dist/async.js:1019:9

    at Object.eachOfLimit (/home/aravind/Tools/cloudsploit/node_modules/async/dist/async.js:1044:24)

    at /home/aravind/Tools/cloudsploit/collectors/aws/collector.js:88:19 {

  code: 'TypeError',

  time: 2024-09-10T09:18:39.384Z

}



Node.js v21.6.1

Tried with the v3.4.0 also, getting the same error
