### ISSUE TITLE
error when running scan

### ISSUE THREAD

**Issue by krynn1** [aquasecurity/cloudsploit#329]
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'tty-table'
Require stack:
- /Users/jason/nic/scans/postprocess/output.js
- /Users/jason/nic/scans/engine.js
- /Users/jason/nic/scans/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/jason/nic/scans/postprocess/output.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jason/nic/scans/postprocess/output.js',
    '/Users/jason/nic/scans/engine.js',
    '/Users/jason/nic/scans/index.js'
  ]
}

**Comment by krynn1** [comment]
sorry I needed to reclone it down
