### ISSUE TITLE
"Error [TypeError]: Cannot read property 'length' of undefined" While running the scans

### ISSUE THREAD

**Issue by afonso** [aquasecurity/cloudsploit#399]
```
docker run -e AWS_ACCESS_KEY_ID=xxx -e AWS_SECRET_ACCESS_KEY=xxx cloudsploit --ignore-ok

   _____ _                 _  _____       _       _ _
  / ____| |               | |/ ____|     | |     (_) |
 | |    | | ___  _   _  __| | (___  _ __ | | ___  _| |_
 | |    | |/ _ \| | | |/ _` |\___ \| '_ \| |/ _ \| | __|
 | |____| | (_) | |_| | (_| |____) | |_) | | (_) | | |_
  \_____|_|\___/ \__,_|\__,_|_____/| .__/|_|\___/|_|\__|
                                   | |
                                   |_|

  CloudSploit by Aqua Security, Ltd.
  Cloud security auditing for AWS, Azure, GCP, Oracle, and GitHub

INFO: No config file provided, using default AWS credential chain.
INFO: Ignoring passing results
INFO: Skipping AWS pagination mode
INFO: Determining API calls to make...
INFO: Found 140 API calls to make for aws plugins
INFO: Collecting metadata. This may take several minutes...
INFO: Metadata collection complete. Analyzing...
INFO: Analysis complete. Scan report to follow...
/var/scan/cloudsploit/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error [TypeError]: Cannot read property 'length' of undefined
    at /var/scan/cloudsploit/engine.js:138:30
    at Object.run (/var/scan/cloudsploit/plugins/aws/autoscaling/webTierAsgAssociatedElb.js:27:46)
    at /var/scan/cloudsploit/engine.js:137:20
    at /var/scan/cloudsploit/node_modules/async/dist/async.js:3682:9
    at replenish (/var/scan/cloudsploit/node_modules/async/dist/async.js:1011:17)
    at /var/scan/cloudsploit/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/var/scan/cloudsploit/node_modules/async/dist/async.js:1041:24)
    at Object.mapValuesLimit (/var/scan/cloudsploit/node_modules/async/dist/async.js:3681:5)
    at /var/scan/cloudsploit/engine.js:134:15
    at /var/scan/cloudsploit/collectors/aws/collector.js:1281:13 {
  code: 'TypeError',
  time: 2020-10-26T21:07:55.185Z
}
```

**Comment by vgostyuzhov-cf** [comment]
I encountered the exact same error.

**Comment by VGostyuzhov** [comment]
I encountered the exact same error.

**Comment by nickbabkin** [comment]
Same error here.

**Comment by n33dle** [comment]
Same thing here too

**Comment by bikashorissa** [comment]
Same thing here too

**Comment by bikashorissa** [comment]
I am using the product so any resolution for this can help me out

**Comment by christophetd** [comment]
Same here.

**Comment by dalenewman** [comment]
As a work around, you could run `git checkout v2.0.0` and try again.

**Comment by giorod3** [comment]
Thank you for reporting this, we have identified the issue and we will be issuing a fix for this.

**Comment by giorod3** [comment]
hotfix for this issue: #426
