### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by battagiri** [aquasecurity/cloudsploit#407]
Hi , I am getting the following error. please help

INFO: No config file provided, using default AWS credential chain.
INFO: Ignoring passing results
INFO: Skipping AWS pagination mode
INFO: Determining API calls to make...
INFO: Found 142 API calls to make for aws plugins
INFO: Collecting metadata. This may take several minutes...
INFO: Metadata collection complete. Analyzing...
INFO: Analysis complete. Scan report to follow...
C:\cloudsploit\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

Error [TypeError]: Cannot read property 'length' of undefined
    at C:\cloudsploit\engine.js:138:30
    at Object.run (C:\cloudsploit\plugins\aws\autoscaling\webTierAsgAssociatedElb.js:27:46)
    at C:\cloudsploit\engine.js:137:20
    at C:\cloudsploit\node_modules\async\dist\async.js:3682:9
    at replenish (C:\cloudsploit\node_modules\async\dist\async.js:1011:17)
    at C:\cloudsploit\node_modules\async\dist\async.js:1016:9
    at eachOfLimit (C:\cloudsploit\node_modules\async\dist\async.js:1041:24)
    at Object.mapValuesLimit (C:\cloudsploit\node_modules\async\dist\async.js:3681:5)
    at C:\cloudsploit\engine.js:134:15
    at C:\cloudsploit\collectors\aws\collector.js:1329:13 {
  code: 'TypeError',
  time: 2020-11-10T07:37:03.364Z
}

**Comment by n33dle** [comment]
Also getting the same error

`INFO: Analysis complete. Scan report to follow...
/home/<redacted>/cloudsploit/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error [TypeError]: Cannot read property 'length' of undefined
    at /home/<redacted>/cloudsploit/engine.js:138:30
    at Object.run (/home/<redacted>/cloudsploit/plugins/aws/autoscaling/webTierAsgAssociatedElb.js:27:46)
    at /home/<redacted>/cloudsploit/engine.js:137:20
    at /home/<redacted>/cloudsploit/node_modules/async/dist/async.js:3682:9
    at replenish (/home/<redacted>/cloudsploit/node_modules/async/dist/async.js:1011:17)
    at /home/<redacted>/cloudsploit/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/home/<redacted>/cloudsploit/node_modules/async/dist/async.js:1041:24)
    at Object.mapValuesLimit (/home/<redacted>/cloudsploit/node_modules/async/dist/async.js:3681:5)
    at /home/<redacted>/cloudsploit/engine.js:134:15
    at /home/<redacted>/cloudsploit/collectors/aws/collector.js:1329:13 {
  code: 'TypeError',
  time: 2020-11-16T02:43:12.910Z
}`

**Comment by giorod3** [comment]
closing because this is a duplicate of #399
