### ISSUE TITLE
Error loading config file

### ISSUE THREAD

**Issue by danilocasabona** [aquasecurity/cloudsploit#498]
INFO: Using CloudSploit config file: config.js
ERROR: Config file could not be loaded. Please ensure you have copied the config_example.js file to config.js

Does someone knows why I am unable to load the config.js file? I did all the steps listed in the instructions.

**Comment by michael-malenkov** [comment]
It seems that it requires an absolute path to the config file, probably depends on system and setup and providing an absolute path to the config.js works 100% of times

**Comment by righteousgambitresearch** [comment]
> It seems that it requires an absolute path to the config file, probably depends on system and setup and providing an absolute path to the config.js works 100% of times

I have set absolute path running Node on Windows and it will not load the config file. Not sure what the issue is there...

**Comment by michael-malenkov** [comment]
Hm, I just ran on both Mac and Windows and both worked. Make sure you specifying an absolute path in command-line/terminal. 
On Mac/Linux it's $./ingex.js --config /absolute/path/to/config.js
On Windows: node ingex.js --config /absolute/path/to/config.js
![2021-01-25 (2)](https://user-images.githubusercontent.com/5079108/105798699-c2861b80-5f60-11eb-8aad-02f4542d39dc.png)

**Comment by danilocasabona** [comment]
I did set the absolute path to config file, but still not working...
<img width="802" alt="Captura de Tela 2021-01-26 às 13 03 16" src="https://user-images.githubusercontent.com/50963588/105870408-01ef4f00-5fd7-11eb-83e9-0f368191446c.png">

**Comment by hxhBrofessor** [comment]
i'm getting the same error as well

**Comment by hxhBrofessor** [comment]
// CloudSploit config file

module.exports = {
    credentials: {
        aws: {
            // OPTION 1: If using a credential JSON file, enter the path below
             credential_file: '~/.aws/cSploit.js'
            // OPTION 2: If using hard-coded credentials, enter them below
            // access_key: process.env.AWS_ACCESS_KEY_ID || '',
            // secret_access_key: process.env.AWS_SECRET_ACCESS_KEY || '',
            // session_token: process.env.AWS_SESSION_TOKEN || '',
            // plugins_remediate: ['bucketEncryptionInTransit']
        }        
    }
};

**Comment by bestrocker221** [comment]
Getting the same error, on arch linux. 
pointing the credential_file to a json as specified by the README, and still getting error.

Result? I can't use the tool

**Comment by sentinelmangcp** [comment]
Same

**Comment by sou2cute** [comment]
> 
> 
> Hm, I just ran on both Mac and Windows and both worked. Make sure you specifying an absolute path in command-line/terminal.
> On Mac/Linux it's $./ingex.js --config /absolute/path/to/config.js
> On Windows: node ingex.js --config /absolute/path/to/config.js
> 
> ![2021-01-25 (3)](https://user-images.githubusercontent.com/5079108/105798765-e5b0cb00-5f60-11eb-89aa-e3f262be8352.png)

This works for me, thanks.

from `~/cloudsploit $ ./index.js --config=config.js`
to     `~/cloudsploit $ ./index.js --config=$(pwd)/config.js`

**Comment by RahulRaval28** [comment]
> Hm, I just ran on both Mac and Windows and both worked. Make sure you specifying an absolute path in command-line/terminal. On Mac/Linux it's $./ingex.js --config /absolute/path/to/config.js On Windows: node ingex.js --config /absolute/path/to/config.js
> 
> ![2021-01-25 (3)](https://user-images.githubusercontent.com/5079108/105798765-e5b0cb00-5f60-11eb-89aa-e3f262be8352.png)

Can You Elaborate Why We have to Specify The Absolute Path ??

**Comment by blackbrownco** [comment]
i have specified a hardcoded alibaba AK and ASK but got this error:
`ERROR: Config file does not contain any valid credential configs.`

Also, i tried to point where config.json of alibaba cloud account stored also got this error:
`INFO: Using CloudSploit config file: /home/altodia/Tools/cloudsploit/config.js
INFO: Skipping AWS pagination mode
INFO: Determining API calls to make...
INFO: Found 37 API calls to make for alibaba plugins
INFO: Collecting metadata. This may take several minutes...
/home/altodia/Tools/cloudsploit/node_modules/ali-oss/lib/common/client/initOptions.js:24
    throw new Error('require accessKeyId, accessKeySecret');
    ^

Error: require accessKeyId, accessKeySecret
    at module.exports (/home/altodia/Tools/cloudsploit/node_modules/ali-oss/lib/common/client/initOptions.js:24:11)
    at Function.initOptions (/home/altodia/Tools/cloudsploit/node_modules/ali-oss/lib/client.js:60:10)
    at new Client (/home/altodia/Tools/cloudsploit/node_modules/ali-oss/lib/client.js:33:27)
    at module.exports [as listBuckets] (/home/altodia/Tools/cloudsploit/collectors/alibaba/oss/listBuckets.js:6:19)
    at /home/altodia/Tools/cloudsploit/collectors/alibaba/collector.js:372:54
    at /home/altodia/Tools/cloudsploit/node_modules/async/dist/async.js:3113:16
    at replenish (/home/altodia/Tools/cloudsploit/node_modules/async/dist/async.js:1014:17)
    at /home/altodia/Tools/cloudsploit/node_modules/async/dist/async.js:1019:9
    at Object.eachLimit$1 (/home/altodia/Tools/cloudsploit/node_modules/async/dist/async.js:3199:24)
    at /home/altodia/Tools/cloudsploit/collectors/alibaba/collector.js:363:19

Node.js v20.17.0
`
