### ISSUE TITLE
Collecting metadata. This may take several minutes... events.js:292       throw er; // Unhandled 'error' event       ^  Error: connect ETIMEDOUT 138.1.16.150:443

### ISSUE THREAD

**Issue by Aditya21jan** [aquasecurity/cloudsploit#569]
HI Team,

We have installed and configured the cloudsploit tool with Oracle Cloud Infrastructure (OCI), While generating the command we are getting below error connect ETIMEOUT Error and also noticed that every time  the destination IP address is getting change.

**Could you please provide the specific IP address range that need to be whitelist in the egress rule and Route table of the instance to resolve and fix this connection TIMEOUT Error from OCI compute Instance towards the Internet.**

**We have not added the 0.0.0.0 route and egress rule in the existing route table & security list due to security concern.** 

######## Console log ########
[root@ins01 cloudsploit-master]#
[root@ins01 cloudsploit-master]# ./index.js --config /home/cloudtool/cloudsploit-master/config.js

   _____ _                 _  _____       _       _ _
  / ____| |               | |/ ____|     | |     (_) |
 | |    | | ___  _   _  __| | (___  _ __ | | ___  _| |_
 | |    | |/ _ \| | | |/ _` |\___ \| '_ \| |/ _ \| | __|
 | |____| | (_) | |_| | (_| |____) | |_) | | (_) | | |_
  \_____|_|\___/ \__,_|\__,_|_____/| .__/|_|\___/|_|\__|
                                   | |
                                   |_|

  CloudSploit by Aqua Security, Ltd.
  Cloud security auditing for AWS, Azure, GCP, Oracle, and GitHub

INFO: Using CloudSploit config file: /home/cloudtool/cloudsploit-master/config.js
INFO: Skipping AWS pagination mode
INFO: Determining API calls to make...
INFO: Found 38 API calls to make for oracle plugins
INFO: Collecting metadata. This may take several minutes...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 147.154.238.120:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '147.154.238.120',
  port: 443
}
[root@ins01 cloudsploit-master]#
[root@ins01 cloudsploit-master]#

Br,
Aditya Singh.
9945549518.

**Comment by Aditya21jan** [comment]
HI Team,

Could you please update the same.

Br,
Aditya Singh.
9945549518.

**Comment by ismaelalfarojr** [comment]
How was this resolved? I am getting same errors.
