### ISSUE TITLE
TypeError: regionVal.data.forEach is not a function

### ISSUE THREAD

**Issue by szEvEz** [aquasecurity/cloudsploit#576]
It seems like with the [latest commits to master](https://github.com/aquasecurity/cloudsploit/commit/43b32ab9abe4b8d2fcae5034625c34f451155067) it is not working anymore.

Running 

```sh
./index.js --config ./config.js --compliance=cis
```

results into the following error:

```sh
INFO: Found 20 API calls to make for aws plugins
INFO: Collecting metadata. This may take several minutes...
INFO: Metadata collection complete. Analyzing...
INFO: Analysis complete. Scan report to follow...
INFO: Using custom ASL for plugin: Access Keys Last Used
INFO: Using custom ASL for plugin: Access Keys Rotated
INFO: Using custom ASL for plugin: Minimum Password Length
/opt/workspace/cloudsploit/cloudsploit/helpers/asl.js:234
            regionVal.data.forEach(function(regionData) {
                           ^

TypeError: regionVal.data.forEach is not a function
    at asl (/opt/workspace/cloudsploit/cloudsploit/helpers/asl.js:234:28)
    at /opt/workspace/cloudsploit/cloudsploit/engine.js:200:17
    at /opt/workspace/cloudsploit/cloudsploit/node_modules/async/dist/async.js:3682:9
    at replenish (/opt/workspace/cloudsploit/cloudsploit/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/opt/workspace/cloudsploit/cloudsploit/node_modules/async/dist/async.js:995:17)
    at /opt/workspace/cloudsploit/cloudsploit/node_modules/async/dist/async.js:969:16
    at /opt/workspace/cloudsploit/cloudsploit/node_modules/async/dist/async.js:3685:13
    at Timeout._onTimeout (/opt/workspace/cloudsploit/cloudsploit/engine.js:193:41)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by nickbabkin** [comment]
+1. Same issue.

**Comment by szEvEz** [comment]
Looks like its working again. Will close issue.
